#' Calculating PVE from mixed-model's results
#'
#' A function to calculate PVE by DGE, IGE, and their covariance based on the output of \code{EM3.cov()}
#' @param x A output of \code{neiEM3.cov()}.
#' @return Proportion of phenotypic variation explained (PVE) by direct genetic effects (DGEs), indirect genetic effects (IGEs), and their covariance (cov).
#' @author Yasuhiro Sato (\email{sato.yasuhiro.36c@kyoto-u.jp})
#' @export
calcPVE.cov = function(x){
  if((is.list(x)==TRUE)&(length(x)==13)){
    PVEtot <- x$Vu/(x$Vu+x$Ve)
    PVEdge <- PVEtot*x$weights[1]
    PVEige <- PVEtot*x$weights[2]
    PVEcov <- PVEtot*(x$rhosMat[1,2]*sqrt(x$weights[1]*x$weights[2]))
    res <- c(PVEdge,PVEige,PVEcov)
    names(res) <- c("PVEdge","PVEige","PVEcov")
  } else {
    stop("x must be a list object generated by the neiEM3.cov function")
  }
  return(res)
}
