#' Creating Manhattan plot from GWAS output
#'
#' A function to dipict GWAS Manhattan plot
#' @param chr Chromosomal positions. Non-numeric allowed.
#' @param pos Genomic positions in base pairs within chromosomes.
#' @param p GWAS p-values ranging from 0 to 1.
#' @return Manhattan plot generated by \code{ggplot2} package
#' @details
#' For genome-wide threshold, dashed and solid lines indicate FDR and Bonferroni threshold, respectively.
#' The latter is provided.when FDR is not detected by \code{RAINBOWR::CalcTreshold()}.
#' @author Yasuhiro Sato (\email{sato.yasuhiro.36c@kyoto-u.jp})
#' @export
ggMan = function(chr,pos,p){
  x <- coord(chr,pos)
  if(length(pos)!=length(p)) stop("pos and p length differ")
  if(max(p,na.rm=TRUE)>1) stop("p-values must be less than 1")

  chr_rep <- table(chr)
  cols <- rep(rep(c(grDevices::grey(0.5,0.5),"black"),times=length(chr_rep)/2),times=chr_rep)
  th <- RAINBOWR::CalcThreshold(input=data.frame(name=c(1:length(p)),chr=chr,pos=pos,p=-log10(p)))
  lty <- 2
  if(is.na(th)) {
    th <- -log10(0.05/length(p))
    lty <- 1
  }

  man <- ggplot2::ggplot(NULL,ggplot2::aes(x=x$coord,y=-log10(p))) + ggplot2::geom_point(colour=cols,alpha=0.5) + ggplot2::theme_classic() +
    ggplot2::scale_x_continuous(name="Chromosomes", breaks=x$tic, labels=names(chr_rep)) +
    ggplot2::ylab(expression(-log[10]*(italic(p)))) + ggplot2::geom_hline(yintercept=th,lty=lty,colour="grey")

  return(man)
}
