#' Creating Manhattan plot from GWAS output
#'
#' A function to dipict GWAS QQ plot
#' @param p GWAS p-values ranging from 0 to 1.
#' @return QQ plot generated by \code{ggplot2} package
#' @author Yasuhiro Sato (\email{sato.yasuhiro.36c@kyoto-u.jp})
#' @export
ggQQ = function(p){
  if(max(p,na.rm=TRUE)>1) stop("p-values must be less than 1")

  o <- -log(sort(p,decreasing=FALSE),10)
  e <- -log(stats::ppoints(length(p)),10)
  qq <- ggplot2::ggplot(data=NULL, mapping=ggplot2::aes(x=e,y=o))+
    ggplot2::geom_point(alpha=0.5)+
    ggplot2::geom_abline(intercept=0,slope=1,linetype="dashed") + ggplot2::theme_classic()+
    ggplot2::xlab(expression("Expected "*-log[10](p))) +
    ggplot2::ylab(expression("Observed "*-log[10](p)))

  return(qq)
}

