#' Mixed models for testing self and neighbor effects with their covariance
#'
#' A function to provide coefficients and p-values of self and neighbor effects for each marker.
#' @param geno An individual x marker matrix. Bialleles (i.e., A or a) must be converted into -1 or 1 digit.
#' @param g_nei An output of \code{nei_coval()} object, namely an individual x marker matrix including neighbor genotypic identity.
#' @param pheno A numeric vector including phenotypes for individuals
#' @param X0 An optional matrix including additional non-genetic covariates. It contains no. of individuals x no. of covariates.
#' @param ... Arguments to be passed to \code{EM3.cov()}.
#' @return A list object generated by \code{EM3.cov()} as well as its LL-ratio and p-value over the model without covariance (rho).
#' @author Yasuhiro Sato (\email{sato.yasuhiro.36c@kyoto-u.jp}) and Kosuke Hamazaki
#' @export
neiEM3.cov = function(geno, g_nei, pheno, X0=matrix(1,nrow=length(pheno)), ...){
  if((min(geno)==-1)&(max(geno)==1)){
    if((min(g_nei)==-1)&(max(g_nei)==1)){
      message("genotype data, ok")
    }
  } else {
    stop("genotype values must range from -1 to +1")
  }

  q <- ncol(geno)

  selfCross <- tcrossprod(geno)
  K1 <- (q+selfCross)/(2*(q-1))

  neiCross <- tcrossprod(g_nei)
  K2 <- neiCross/(q-1)

  K12 <- tcrossprod(geno,g_nei)/(q-1)
  K21 <- t(K12)

  ind_names <- paste0("ind",1:length(pheno))
  Z <- diag(length(pheno))

  y <- as.matrix(pheno)
  rownames(y) <- ind_names
  rownames(Z) <- ind_names
  colnames(Z) <- ind_names
  rownames(K1) <- ind_names
  colnames(K1) <- ind_names
  rownames(K2) <- ind_names
  colnames(K2) <- ind_names
  ZETA1 <- list(A = list(Z = Z, K = K1),
                Int = list(Z = Z, K = K2))

  rownames(K12) <- ind_names
  colnames(K12) <- ind_names
  rownames(K21) <- ind_names
  colnames(K21) <- ind_names

  covList1 <- rep(list(rep(list(NULL), 2)), 2)
  covList1[[1]][[2]] <- K12
  covList1[[2]][[1]] <- K21

  rownames(X0) <- ind_names

  message("LMM is being solved...")
  EM3.res11 <- RAINBOWR::EM3.cpp(y = y,
                       X0 = X0,
                       ZETA = ZETA1)
  w = EM3.res11$weights
  if(sum(w==TRUE)==1) {
    w[w==1] = 0.99
    w[w==0] = 0.01
  }

  args <- list(...)
  args$y <- y
  args$X0 <- X0
  args$ZETA <- ZETA1
  args$covList <- covList1
  args$parInitForWeights <- w
  EM3.res12 <- do.call(RAINBOWR::EM3.cov, args)

  chi2 <- -2*(EM3.res11$LL-EM3.res12$LL)
  p <- stats::pchisq(chi2,1,lower.tail=FALSE)

  EM3.res12$chi2 <- chi2
  EM3.res12$pval <- p
  message("LMM, done.")

  return(EM3.res12)
}
